apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS inventory_table (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      count INT NOT NULL
    );