apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: naveensachdeva/nagp-nodejs-app:v1.1
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: nodejs-app-config